# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

## **Part 1**

#### 1. Import the numpy package under the name `np`


In [1]:
# Apostol, Gian Tristian G.
# Cabangbang, R-Man Rey S.
import numpy as np

#### 2. Print the numpy version

In [2]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [14]:
array = np.empty(5)
array

array([3.47739925e-081, 1.15433723e-071, 1.16413893e+165, 1.11600072e+165,
       4.01844696e-057])

#### 4. Create a null array of size 15 but the seventh value which is 1

In [15]:
array = np.empty( 15 )
array[ 6 ] = 1
array

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [13]:
arr = np.array([
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ],
    [ 1, 2, 3, 4 ]
])
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [17]:
arr = np.array( [ 1, 2, 4, 0, 4, 0 ] )
search = np.where( arr != 0 )
search

(array([0, 1, 2, 4]),)

#### 7. Create a 4x4x4 array with random values

In [16]:
from numpy import random
arr = random.rand( 4, 4, 4 )
arr

array([[[0.69286962, 0.2556442 , 0.8912102 , 0.15022489],
        [0.78146884, 0.15727709, 0.05285036, 0.5014825 ],
        [0.95948384, 0.0889169 , 0.6492296 , 0.49774464],
        [0.80211148, 0.99920959, 0.02583082, 0.27271434]],

       [[0.90511851, 0.11548915, 0.66762495, 0.03279614],
        [0.9124751 , 0.18854665, 0.87701082, 0.25945794],
        [0.10125611, 0.18683587, 0.69036535, 0.90234614],
        [0.41655898, 0.6850218 , 0.89063281, 0.08443882]],

       [[0.543411  , 0.849078  , 0.5561289 , 0.74990409],
        [0.7085788 , 0.99241442, 0.6396244 , 0.71796502],
        [0.50614886, 0.27806587, 0.89032596, 0.00706948],
        [0.7766011 , 0.40910503, 0.36226227, 0.47919874]],

       [[0.47136284, 0.52296765, 0.20245091, 0.25977978],
        [0.75681151, 0.15858691, 0.91133702, 0.12000918],
        [0.944159  , 0.83555288, 0.88484218, 0.97675365],
        [0.44133224, 0.76276795, 0.76263484, 0.38674803]]])

#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [22]:
arr = random.rand( 15, 15 )
min = np.min( arr )
print( "Min:", min )


Min: 0.0011265650893269585


In [23]:
max = np.max( arr )
print( "Max:", max )

Max: 0.9814901078439126


#### 9. Create a random array of size 25 and find the mean value

In [24]:
arr = random.rand( 25 )
np.mean( arr )

np.float64(0.44006101144077564)

#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [28]:
a = np.array( [ 2, 4, 9 ] )
b = np.array( [ 1, 14, 6 ] )

10.1 What is the result of *a + b*?

In [29]:
a + b

array([ 3, 18, 15])

10.2 What is the result of *a - b*?

In [30]:
a - b

array([  1, -10,   3])

10.3 What is the result of *a × b*?

In [31]:
a * b

array([ 2, 56, 54])

10.4 What is the result of *a ÷ b*?

In [32]:
a / b

array([2.        , 0.28571429, 1.5       ])

## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [33]:
arr = np.array( [
    [ 10, 20, 30 ],
    [ 40, 50, 60 ],
    [ 70, 80, 90 ]
] )

1. Write code to extract the element 50.

In [35]:
arr[1,1]

np.int64(50)

2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [37]:
arr[1]

array([40, 50, 60])

3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [38]:
arr[:,2]

array([30, 60, 90])

4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [39]:
arr[1:,1:]

array([[50, 60],
       [80, 90]])

##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [41]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [42]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [43]:
arr[0,::2]

array([1, 3])

4. Write code to reverse the order of rows in the matrix

In [44]:
np.flip( arr )

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

5. Write code to extract the last two columns of the matrix.

In [45]:
arr[:, 2:4]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [46]:
arr1 = np.array([11,7,33])
arr2 = np.array([44,5,18])

2. Write code to join arr1 and arr2 into a single 1D array.

In [48]:
arr = np.concatenate((arr1,arr2))
arr

array([11,  7, 33, 44,  5, 18])

3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [49]:
arr = np.stack((arr1,arr2))
arr

array([[11,  7, 33],
       [44,  5, 18]])

4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [50]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

5. Write code to join them horizontally (column-wise).

In [51]:
arr = np.hstack((arr1,arr2))

arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [52]:
arr = np.vstack((arr1,arr2))

arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [96]:
arr1 = np.linspace( 10, 28, 10 )
print( "1.", arr1.astype( 'i' ),"\n" )

arr2 = random.randint(1,51, size=( 4, 4 ) )
print("2.", arr2,"\n")

arr3 = np.ones((2,3,4))
print("3.", arr3)

1. [10 12 14 16 18 20 22 24 26 28] 

2. [[39 44 41 40]
 [30 19  4 17]
 [31 46 34 42]
 [49  7 23 17]] 

3. [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [105]:
newarr = arr1.reshape(2,5)
newarr[ np.where(newarr%2==0) ] = -1
print( newarr )

[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [115]:
print( "Mean:", np.mean( arr2 ) )
print( "Median:", np.median( arr2 ))
print( "Standard Deviation:", np.std( arr2 ))

np.sum( arr2, axis=1 )

print( "Max:", np.max( arr2 ) )
print( "Max Index:", np.argmax( arr2 ) )

Mean: 30.1875
Median: 32.5
Standard Deviation: 13.6666507875924
Max: 49
Max Index: 12


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [148]:
arr = random.rand( 10, 10 )
print("Minimum value along each column:", np.min( arr, axis=0))

flattened = arr.flatten()
indices = np.argsort( flattened )[::-1][:5]

print( "Indices of the top 5 largest values:", indices )

Minimum value along each column: [0.05430594 0.0774948  0.05173689 0.02008462 0.06665376 0.12216948
 0.01245165 0.24692204 0.1261774  0.03253217]
Indices of the top 5 largest values: [73 28 21 26 75]
